services:
  # SERVEI 1: API
  api:
    build: .
    container_name: scav-api
    ports:
      - "8000:80"
    volumes:
      - ./shared_data:/shared # Carpeta compartida
      - /var/run/docker.sock:/var/run/docker.sock # PERMET CONTROLAR DOCKER
    depends_on:
      - ffmpeg-service

  # SERVEI 2: Contenidor FFmpeg
  ffmpeg-service:
    build: ./ffmpeg
    container_name: ffmpeg-service
    volumes:
      - ./shared_data:/shared # Mateixa carpeta compartida
    entrypoint: ["tail", "-f", "/dev/null"] # Esperar més ordres